### ISSUE TITLE
webots file

### ISSUE THREAD

**Issue by xxchenchen** [ammackenzie/Webots-Universal-Controller-and-Evolutionary-Robotics-Suite#1]
Hi

There is no webots (wbt file). 

How can i apply them? Thanks

**Comment by ammackenzie** [comment]
Hi,

Thanks for getting in touch, the project is a work in progress and I will continue to update and foolproof the instructions and code.

I've recently updated the set up instructions in the read me. There is a link to the Webots website to install Webots itself first as it is not provided in this project.

This project is a controller that can be used with any wheeled robot and allows for easy Reinforcement Learning experimentation with some select algorithms and neural networks.

Here are the updated instructions on the read me:
Prerequisites

  1.  Install Webots<https://cyberbotics.com/doc/guide/installation-procedure>
  2.  Install Python<https://www.python.org/downloads/windows/>: [https://www.python.org/downloads/windows/] (make sure supplementary libraries: NumPy, SciPy, Matplotlib, pickle are also installed)
  3.  Install the Deap library<https://deap.readthedocs.io/en/master/installation.html>:
  4.  Place the entire 'UniversalController' folder inside of your 'Controllers' folder in your Webots projects directory (WebotsProjects>YourProject>controllers>UniversalController)
  5.  Basic understanding of how to set up a Webots Environment and change robot controllers<https://cyberbotics.com/doc/guide/tutorial-1-your-first-simulation-in-webots>

<https://github.com/ammackenzie/Webots-Universal-Controller-and-Reinforcement-Learning-Suite/blob/master/README.md#set-up>Set up

  1.  Once you have place the 'UniversalController' folder inside your controller folder, you can now select 'UniversalController' as a controller option for your robot
  2.  Open up the UniversalController.py module in either the Webots editor or an IDE of your choice
  3.  The only information you need access to is the names of the distance sensors built into your robot - this can be found via the Webots documentation<https://cyberbotics.com/doc/guide/robots> on the available robots
  4.  Follow the instructions below or the step by step comments in the file itself to begin experimentation with just a few lines of code, or simply edit the existing code or example code provided in the comments


Please let me know if this helps, if not I can help troubleshoot.

Regards,
Andrew
________________________________

**Comment by xxchenchen** [comment]
Thanks
